### ISSUE TITLE
Proposal: more defined tasks

### ISSUE THREAD

**Issue by Richard87** [meolu/walle-web#59]
Split pre-release, link, post-release in different tasks for better feedback if something goes wrong and more acurate progress bar

What do you think?

**Comment by meolu** [comment]
They are separated at first. but they are combined by me, because it is a better way to accomplish all the jobs in target servers.

The progress bar can be calculated the target servers which is done, there are many servers for a service generally, but it is hard to show the progress of this deployment, because the unit of deployment is task not servers, and the last task is a task group running in multiple servers, so I name it task group as **update** as last step.

it will tell user the problem occured in which server if something goes wrong.

**Comment by Richard87** [comment]
yeah, I will test a little more, but so far it hasn't included any of the error messages that occur, only that something wrong happened (inspecting data from console shows the error though)...

Starting to believe there is something wrong with the UI on my installation...
