### ISSUE TITLE
Feedback if start_deploy fails

### ISSUE THREAD

**Issue by Richard87** [meolu/walle-web#60]
Hi!

If start_deploy fails it will never finish, had some problem figuring this one out before noticing that one failed with either a gateway timeout (504) or "MySQL server has gone away" (500) or something else...

My solution was adding a timeout in nginx:
    proxy_connect_timeout 240;
    proxy_read_timeout 240;

MySQL: 
    max_allowed_packet=320M
    wait_timeout=3600

**Comment by meolu** [comment]
ok, you have found the problem timeout and start_deploy's return, now what I have done is setting php and nginx timeout 0 until start_deploy task finish, there is a poll running to checkout the task's status. I'am trying to write a websocket instead of poll, then, the problem you say would be disappeared, it woud be done in next version.

**Comment by Richard87** [comment]
ah, cool, I though webSockets only would be used for polling status, and not for controlling the start of the job.
